server:
  port: 4100

spring:
  application:
    name: ryuntech-su-cloud-service-saas
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 1
    lettuce:
        pool:
            max-active: 1024
            max-idle: 300
            min-idle: 5
            max-wait: -1
    timeout: 30000
  profiles:
    active: dev
  cloud:
    config:
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
  auth:
    client_id: client
    client_secret: secret
    grant_type: password
  mail:
    host: smtp.qq.com
    username: 851597995@qq.com
    password: wlmjlpiepccvbcgj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  freemarker:
    charset: UTF-8
    allow-request-override: false
    cache: false
    expose-request-attributes: false
    expose-session-attributes: false
    content-type: text/html
    template-loader-path: classpath:/static/template/
    expose-spring-macro-helpers: false
    check-template-location: true
    enabled: true

#security:
#
#  oauth2:
#    client:
#      client-id: client
#      client-secret: secret
#      access-token-uri: http://ryuntech-su-cloud-auth:4000/oauth/token
#      user-authorization-uri: http://ryuntech-su-cloud-auth:4000/oauth/authorize
#    resource:
#      token-info-uri: http://ryuntech-su-cloud-auth:4000/oauth/check_token

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://ryuntech-su-cloud-eureka:8761/eureka/

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

#mybatis配置
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.ryuntech.saas.api.model


mybatis-plus:
    mapper-locations: classpath:/mapper/*Mapper.xml

#mybaatis分页插件pagehelper设置
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true

# 打印sql
logging:
  level:
    com.ryuntech.saas.api.mapper: DEBUG
