server:
  port: 4000

spring:
  application:
    name: ryuntech-su-cloud-authorization
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  cloud:
    config:
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
  auth:
    client_id: client
    client_secret: secret
    grant_type: password
  redis:
    host: 192.168.30.103
    port: 6379
    password: vsxd@redis
    database: 1
    lettuce:
        pool:
            max-active: 1024
            max-idle: 300
            min-idle: 5
            max-wait: -1
    timeout: 30000

# feign 配置
feign:
  hystrix:
    enabled: true
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 80000

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://ryuntech-su-cloud-eureka:8761/eureka/

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
